-- Seed data for US Stocks reference table
-- Run this AFTER running schema.sql in Supabase SQL Editor

INSERT INTO stocks (symbol, name, exchange, sector) VALUES
-- Tech Giants
('AAPL', 'Apple Inc.', 'NASDAQ', 'Technology'),
('MSFT', 'Microsoft Corporation', 'NASDAQ', 'Technology'),
('GOOGL', 'Alphabet Inc. Class A', 'NASDAQ', 'Technology'),
('GOOG', 'Alphabet Inc. Class C', 'NASDAQ', 'Technology'),
('AMZN', 'Amazon.com Inc.', 'NASDAQ', 'Consumer Discretionary'),
('META', 'Meta Platforms Inc.', 'NASDAQ', 'Technology'),
('NVDA', 'NVIDIA Corporation', 'NASDAQ', 'Technology'),
('TSLA', 'Tesla Inc.', 'NASDAQ', 'Consumer Discretionary'),
('AMD', 'Advanced Micro Devices Inc.', 'NASDAQ', 'Technology'),
('INTC', 'Intel Corporation', 'NASDAQ', 'Technology'),
('ORCL', 'Oracle Corporation', 'NYSE', 'Technology'),
('CRM', 'Salesforce Inc.', 'NYSE', 'Technology'),
('ADBE', 'Adobe Inc.', 'NASDAQ', 'Technology'),
('NFLX', 'Netflix Inc.', 'NASDAQ', 'Communication Services'),
('PYPL', 'PayPal Holdings Inc.', 'NASDAQ', 'Financials'),
('SQ', 'Block Inc.', 'NYSE', 'Financials'),
('SHOP', 'Shopify Inc.', 'NYSE', 'Technology'),
('UBER', 'Uber Technologies Inc.', 'NYSE', 'Technology'),
('LYFT', 'Lyft Inc.', 'NASDAQ', 'Technology'),
('SNAP', 'Snap Inc.', 'NYSE', 'Communication Services'),
('PINS', 'Pinterest Inc.', 'NYSE', 'Communication Services'),
('SPOT', 'Spotify Technology S.A.', 'NYSE', 'Communication Services'),
('ZM', 'Zoom Video Communications', 'NASDAQ', 'Technology'),
('DOCU', 'DocuSign Inc.', 'NASDAQ', 'Technology'),
('PLTR', 'Palantir Technologies Inc.', 'NYSE', 'Technology'),
('SNOW', 'Snowflake Inc.', 'NYSE', 'Technology'),
('CRWD', 'CrowdStrike Holdings Inc.', 'NASDAQ', 'Technology'),
('NET', 'Cloudflare Inc.', 'NYSE', 'Technology'),
('DDOG', 'Datadog Inc.', 'NASDAQ', 'Technology'),
('MDB', 'MongoDB Inc.', 'NASDAQ', 'Technology'),

-- Financial
('JPM', 'JPMorgan Chase & Co.', 'NYSE', 'Financials'),
('BAC', 'Bank of America Corp.', 'NYSE', 'Financials'),
('WFC', 'Wells Fargo & Company', 'NYSE', 'Financials'),
('C', 'Citigroup Inc.', 'NYSE', 'Financials'),
('GS', 'Goldman Sachs Group Inc.', 'NYSE', 'Financials'),
('MS', 'Morgan Stanley', 'NYSE', 'Financials'),
('V', 'Visa Inc.', 'NYSE', 'Financials'),
('MA', 'Mastercard Incorporated', 'NYSE', 'Financials'),
('AXP', 'American Express Company', 'NYSE', 'Financials'),
('BLK', 'BlackRock Inc.', 'NYSE', 'Financials'),
('SCHW', 'Charles Schwab Corporation', 'NYSE', 'Financials'),

-- Healthcare
('JNJ', 'Johnson & Johnson', 'NYSE', 'Healthcare'),
('UNH', 'UnitedHealth Group Inc.', 'NYSE', 'Healthcare'),
('PFE', 'Pfizer Inc.', 'NYSE', 'Healthcare'),
('ABBV', 'AbbVie Inc.', 'NYSE', 'Healthcare'),
('MRK', 'Merck & Co. Inc.', 'NYSE', 'Healthcare'),
('LLY', 'Eli Lilly and Company', 'NYSE', 'Healthcare'),
('TMO', 'Thermo Fisher Scientific', 'NYSE', 'Healthcare'),
('ABT', 'Abbott Laboratories', 'NYSE', 'Healthcare'),
('DHR', 'Danaher Corporation', 'NYSE', 'Healthcare'),
('BMY', 'Bristol-Myers Squibb', 'NYSE', 'Healthcare'),
('MRNA', 'Moderna Inc.', 'NASDAQ', 'Healthcare'),

-- Consumer
('WMT', 'Walmart Inc.', 'NYSE', 'Consumer Staples'),
('PG', 'Procter & Gamble Company', 'NYSE', 'Consumer Staples'),
('KO', 'Coca-Cola Company', 'NYSE', 'Consumer Staples'),
('PEP', 'PepsiCo Inc.', 'NASDAQ', 'Consumer Staples'),
('COST', 'Costco Wholesale Corp.', 'NASDAQ', 'Consumer Staples'),
('HD', 'Home Depot Inc.', 'NYSE', 'Consumer Discretionary'),
('LOW', 'Lowe''s Companies Inc.', 'NYSE', 'Consumer Discretionary'),
('MCD', 'McDonald''s Corporation', 'NYSE', 'Consumer Discretionary'),
('SBUX', 'Starbucks Corporation', 'NASDAQ', 'Consumer Discretionary'),
('NKE', 'Nike Inc.', 'NYSE', 'Consumer Discretionary'),
('TGT', 'Target Corporation', 'NYSE', 'Consumer Discretionary'),

-- Energy
('XOM', 'Exxon Mobil Corporation', 'NYSE', 'Energy'),
('CVX', 'Chevron Corporation', 'NYSE', 'Energy'),
('COP', 'ConocoPhillips', 'NYSE', 'Energy'),
('SLB', 'Schlumberger Limited', 'NYSE', 'Energy'),
('EOG', 'EOG Resources Inc.', 'NYSE', 'Energy'),

-- Industrial
('CAT', 'Caterpillar Inc.', 'NYSE', 'Industrials'),
('BA', 'Boeing Company', 'NYSE', 'Industrials'),
('HON', 'Honeywell International', 'NASDAQ', 'Industrials'),
('UPS', 'United Parcel Service', 'NYSE', 'Industrials'),
('RTX', 'Raytheon Technologies', 'NYSE', 'Industrials'),
('LMT', 'Lockheed Martin Corp.', 'NYSE', 'Industrials'),
('GE', 'General Electric Company', 'NYSE', 'Industrials'),
('MMM', '3M Company', 'NYSE', 'Industrials'),

-- Communication
('T', 'AT&T Inc.', 'NYSE', 'Communication Services'),
('VZ', 'Verizon Communications', 'NYSE', 'Communication Services'),
('TMUS', 'T-Mobile US Inc.', 'NASDAQ', 'Communication Services'),
('DIS', 'Walt Disney Company', 'NYSE', 'Communication Services'),
('CMCSA', 'Comcast Corporation', 'NASDAQ', 'Communication Services'),

-- ETFs (Major Index Funds)
('SPY', 'SPDR S&P 500 ETF Trust', 'NYSE', 'ETF'),
('QQQ', 'Invesco QQQ Trust', 'NASDAQ', 'ETF'),
('DIA', 'SPDR Dow Jones Industrial Average ETF', 'NYSE', 'ETF'),
('IWM', 'iShares Russell 2000 ETF', 'NYSE', 'ETF'),
('VTI', 'Vanguard Total Stock Market ETF', 'NYSE', 'ETF'),
('VOO', 'Vanguard S&P 500 ETF', 'NYSE', 'ETF'),
('VEA', 'Vanguard FTSE Developed Markets ETF', 'NYSE', 'ETF'),
('VWO', 'Vanguard FTSE Emerging Markets ETF', 'NYSE', 'ETF'),
('GLD', 'SPDR Gold Trust', 'NYSE', 'ETF'),
('SLV', 'iShares Silver Trust', 'NYSE', 'ETF'),
('TLT', 'iShares 20+ Year Treasury Bond ETF', 'NASDAQ', 'ETF'),
('HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'NYSE', 'ETF'),
('XLF', 'Financial Select Sector SPDR Fund', 'NYSE', 'ETF'),
('XLK', 'Technology Select Sector SPDR Fund', 'NYSE', 'ETF'),
('XLE', 'Energy Select Sector SPDR Fund', 'NYSE', 'ETF'),
('XLV', 'Health Care Select Sector SPDR Fund', 'NYSE', 'ETF'),
('ARKK', 'ARK Innovation ETF', 'NYSE', 'ETF')

ON CONFLICT (symbol) DO NOTHING;
